name: Dog Reassignment on M1 Change

on:
  # Triggered by webhook when M1 cell changes
  repository_dispatch:
    types: [m1-changed]
  
  # Manual trigger for testing
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode'
        required: false
        default: 'false'
        type: boolean

jobs:
  reassign-dogs:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas numpy requests gspread google-auth
    
    - name: Run Dog Reassignment System
      run: python production_reassignment.py
      env:
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        TEST_MODE: ${{ github.event.inputs.test_mode }}
        TRIGGER_VALUE: ${{ github.event.client_payload.m1_value }}
    
    - name: Upload logs on any outcome
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: dog-reassignment-logs-${{ github.run_number }}
        path: |
          *.log
          *.csv
          *.json
        retention-days: 7
        if-no-files-found: ignore
